name: Continuous integration

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn install
      - run: yarn test

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: create-release
        with:
          tag_name: ${{ format('{0}-test-release', github.sha) }}
          name: "CI test release"
          body: |
            # Heading

            This is a test release with some markdown.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate that release exists
        run: curl --fail ${{ steps.create-release.outputs.url }}
